"""Added textbooks table test column

Revision ID: d16823541733
Revises: f638cf4b630f
Create Date: 2024-07-27 16:56:36.034587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16823541733'
down_revision: Union[str, None] = 'f638cf4b630f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('textbooks', sa.Column('test', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('textbooks', 'test')
    # ### end Alembic commands ###
