"""Private courses table column renamed

Revision ID: e8ff86ab2620
Revises: dbf112252fe9
Create Date: 2024-07-29 21:11:45.053249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ff86ab2620'
down_revision: Union[str, None] = 'dbf112252fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('private_courses', sa.Column('tutor_course_id', sa.Integer(), nullable=False))
    op.drop_constraint('unique_student_course', 'private_courses', type_='unique')
    op.create_unique_constraint('unique_student_course', 'private_courses', ['student_id', 'tutor_course_id'])
    op.drop_constraint('private_courses_course_id_fkey', 'private_courses', type_='foreignkey')
    op.create_foreign_key(None, 'private_courses', 'tutor_courses', ['tutor_course_id'], ['id'])
    op.drop_column('private_courses', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('private_courses', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'private_courses', type_='foreignkey')
    op.create_foreign_key('private_courses_course_id_fkey', 'private_courses', 'tutor_courses', ['course_id'], ['id'])
    op.drop_constraint('unique_student_course', 'private_courses', type_='unique')
    op.create_unique_constraint('unique_student_course', 'private_courses', ['student_id', 'course_id'])
    op.drop_column('private_courses', 'tutor_course_id')
    # ### end Alembic commands ###
